#!/bin/sh

# Alter this if your compiler is installed somewhere else
F77=gfortran

# Default libraries to use
LIB="-lllmpif -lllmpi"

# Compile / Link
$F77 -fpic -pie -pthread $LIB -Wl,-wrap,pthread_create 
